### ISSUE TITLE
Add single nodes to graph

### ISSUE THREAD

**Issue by artshcherbina** [MaxvdKolk/vimwikigraph#4]
Hello!

I would like to ask the following feature:
Add to graph nodes that don't have inbound and outbound edges.
Currenlty, the are omited.

Best regards,
Artem

**Comment by MaxvdKolk** [comment]
Hi Artem,

I have added the argument `-l` that allows to set the number of edges a node is required to have before being inserted. If you pass `-l 0`, e.g. 
```
./vimwikigraph example -l 0 | dot -Tpng > example.png;
```
nodes without inbound/outbound edges should be drawn as well.

**Comment by artshcherbina** [comment]
Thank you very much for such a fast responce. 
It works as expected.
