### ISSUE TITLE
Path walking fails due to file named .vim-template:project-*

### ISSUE THREAD

**Issue by bergercookie** [MaxvdKolk/vimwikigraph#8]
Hi there, thanks for this tool!

When running it, pointing to the root of my `vimwiki` I get the following error:

```
✦ at 13:06:54 ➜ vimwikigraph . | dot -Tpng > example.png                                                             
2021/05/31 13:07:52 Error when walking directories: open software/.vim-template:project-*: no such file or directory 
```

This is because I have a file literally named  `.vim-template:project-*` under certain directories directories, to use along with this plugin: https://github.com/tibabit/vim-templates

Is there a way to skip these files? For example pass a regex and have `vimiwkigraph` ignore them?

**Comment by MaxvdKolk** [comment]
Hi! Thanks for trying out the tool and reaching out!

Originally there was no approach for ignoring specific files like that. There was a way where any trailing argument was considered as a directory to be ignored, which should now be clarified in the `README`. 

However, I also added the `--ignore` flag that allows you to pass a regex to filter the files. The last example in the `README` shows its usage. Hopefully this helps with ignoring the `.vim-template:project-*` files/directories by passing an appropriate regex using the `--ignore` flag. 

Please let me know if this resolves your issue :-)

**Comment by bergercookie** [comment]
Hi there, haven't tried it yet, but I think it should do the job! Thanks
for the quick resolution!!

Nikos,
